### ISSUE TITLE
Error No Roms Found

### ISSUE THREAD

**Issue by Twitch0815** [singularity098/Generate-MAME-Playlist-for-RetroArch#1]
I am using the mame .78 romset 
# Supply info as appropriate to your collection
$mameRomExtension = '.zip'
$mameRomDir = 'H:\FBAPS3Destination'
$databaseInputFile = 'H:\FBAPS3Destination\MAME 078.dat'
$playlistOutputFile = 'H:\FBAPS3Destination\MAME.lpl' 

I have confirmed that the roms in my directory are in zip format.  
On running the script I am getting Error No Roms Found.
Is there some requirment on merged or non-merged?

**Comment by singularity098** [comment]
Hi Twitch... thanks for providing the variables as you did.  I think that your problem may be a missing backslash at the end of the value for $mameRomDir.   Can you give that a try?

Thanks!

**Comment by Twitch0815** [comment]
Modified too
 Supply info as appropriate to your collection
$mameRomExtension = '.zip'
$mameRomDir = 'H:\FBAPS3Destination\'
$databaseInputFile = 'H:\FBAPS3Destination\MAME 078.dat'
$playlistOutputFile = 'H:\FBAPS3Destination\MAME.lpl'

same error

The directory with the files exists at 
H:\FBAPS3Destination
First rom file is at 
H:\FBAPS3Destination\aerofgt.zip

**Comment by Twitch0815** [comment]
As a test have tried the same thing with the FBA romset FBA 0.2.97.30   

$mameRomExtension = '.zip'
$mameRomDir = 'H:\PiBase-roms\'
$databaseInputFile = 'H:\PiBase-roms\fba\FB Alpha v0.2.97.30.dat'
$playlistOutputFile = 'H:\PiBase-roms\fba\FBAMAME.lpl'

**Comment by singularity098** [comment]
Hmm, that's odd.  Would you mind emailing your dat file and the script to legacy5k@gmail.com?

I am at work right now so probably can't help much until later, but I'm wondering if maybe there is something about your dat file that is different from those that I've been using.  I'm sure I can fix it later....

**Comment by singularity098** [comment]
Hi... I think that I may have fixed your issue, if you'd like to try again.

Originally I was filtering out bad games with logic saying "if driver.status node does not equal 'good', do not process game".  Unfortunately it looks like some of the older dat files do not have this driver element at all, so it would end up being null for all games and since null does not equal good, it processed nothing.  I've changed the logic to explicitly look for the values "preliminary" or "imperfect" and filter only those out, and that way null values are permitted.

Please let me know if you are successful... thanks!!

**Comment by Twitch0815** [comment]
Alright well that is definitely a move in the right direction.  
It processed and spit out a file with the full dat.  
I had to modify 
$checkIfRomsExist = $false   to true in order to get the desired result of only creating a playlist with the names of the games I would want.

Can you add some form of optional flag for when you are going to place that romset in a remote directory.

For example I ran the script on my windows box since it is powershell but I want it to be used on a Softmodded PS3 and the directory structure is much different.

Can there be a commented out file  which replaces the mameRomDir with the desired remote mame directory so that a user would not have to find and replace in the generated playlist file.  

For example the structure in my final file is as follows

H:\FBAPS3Destination\aerofgt.zip
Aero Fighters
DETECT
DETECT
00000001|crc
MAME.lpl
H:\FBAPS3Destination\area51.zip
Area 51
DETECT
DETECT
00000002|crc
MAME.lpl



But I will need to modify it to 
/dev_hdd0/ROMS/mame/aerofgt.zip
Aero Fighters
DETECT
DETECT
00000001|crc
MAME.lpl

Which find and replace should do but would be nice if it could take care of it for you.




Also can you give a little more definition on 
$writeBiosList = $false
With this false it will not include the names of Bios only files?

**Comment by singularity098** [comment]
My bad, I changed $checkIfRomsExist to false so that I could get some output using the old dat files to test your original issue (since I don't have those 078 roms), but forgot to change it back.

Yes I hear you, I could definitely put that flag and variable in for destination directory.  I did the same thing because I've made a playlist for an Nvidia Shield and another Linux machine as well, and had to the same find/replace on the dir path.

Additionally I was thinking about an option to actually copy those ROMs out to a new directory automatically, for instance shaving your 50+ GB collection down to only the 4 GB or so ROMs that you actually want so that they'll fit on your less powerful devices.  I guess I was getting wary though of too many "flags" and variables that a user would have to mess with... but maybe this could work better as an interactive script where it just prompts you Y/N on each option.

The $writeBiosList option will write out a list of filenames for any ROMs that are identified in the XML as having the nodes "runnable=no" and "isdevice=yes", for example qsound.  Those nodes pretty much indicate that it's a BIOS file.  Once I had a list of those filenames, I could pipe that into a foreach loop and copy each of those files out into a new directory.  This gave me about 400 files totaling 9 MB which I could then have accompany my trimmed romset and that way none of the non-clone roms have missing bios files.  That was just me messing around and making it work for myself.  And by the way I noticed that the older dat files don't have those nodes....there's a lot less metadata in the older files, so that probably won't work for your set.

Maybe I will flesh the whole script out a bit more.  I wasn't giving it too much effort because I was just getting it to work for myself knowing that RetroArch itself will incorporate better scanning in the future making this a temporary fix.  But actually since RetroArch will probably never copy ROMs around or sort out bios files for you, this could actually be of some use in the long term.

**Comment by singularity098** [comment]
Hey, I rewrote a great deal of the script incorporating some of your suggestions, if you're interested.  Most of those "flags" are now set by prompting the user during script execution, rather than requiring script editing.

I also added the option to copy only those qualified ROMs to a new directory (effectively trimming the romset down).

It's pretty straightforward, but let me know if you have questions or issues.

Thanks!

**Comment by Twitch0815** [comment]
Let me take a look see if I can make other feature suggestions. 
I have been playing with the list I made for Retroarch 1.3.6 on a PS3  
Some weird things I am trying to get to the bottom of.
I am wondering if the script can generate the data that specifies which core to load to Retroarch so Retroarch does not then prompt you for that data. 
Seems to complicate game switching because I have to exit the game twice once to select the game once to select the core.

**Comment by singularity098** [comment]
Not sure if the PS3 version of RetroArch differs from my version, but this is not specified in the playlist file itself.  Instead you can go to the Settings menu of RetroArch, then select Playlists.  In here, you should see any playlists that you have loaded and can assign whichever core you like to each playlist.

**Comment by Twitch0815** [comment]
Oh that totally worked. 
Ok next hurdle.  Been looking at the AutoHotKey method.  
Basically can you take the code from Auto Hot Key and have it hit a directory of the Snaps and Titles against the roms specified in the rom path in the code, then rename those to friendly images.  


I'm thinking this part of the code.

MAMESnaps = C:\MAME Roms\~SnapsFriendly
;### Full path of MAME snap (gameplay) images with friendly names (generated with Tatsuya79's MAME 
;### image renaming script). This is optional; you only need this if you want gameplay images in RA)

MAMETitles = C:\MAME Roms\~TitlesFriendly
;### Full path of MAME title screen images with friendly names (generated with Tatsuya79's MAME 
;### image renaming script). This is optional; you only need this if you want title screen images in RA)

RAPath = C:\Emulation\RetroArch
;### Full path of Retroarch root folder Ex: C:\Emulation\RetroArch

RAPlayFold = playlists
;### Name (not full path) of desired RetroArch playlists folder   Ex: playlists   Ex: playlists MAME

RAThumbFold = thumbnails
;### Name (not full path) of desired RetroArch thumbnails folder   Ex: thumbnails   Ex: thumbnails MAME

dat = C:\MAME Roms\~MAME - ROMs (v0.176_XML).dat
;### path to a MAME ROM database file
;### example C:\files\MAME - ROMs (v0.164_XML).dat
;### get dat here http://www.emulab.it/rommanager/datfiles.php



This would make the final output of the script include the file pathing information for titles and snaps. 


Another thing though I know not the legal implication is if the script wget the mame snaps and tiles and extracted them before hand. 

What do you think?

**Comment by singularity098** [comment]
Honestly I have never messed around with titles and snaps, and I don't think that I really have the time or desire to dive into that.  The important part to me was just having a readable playlist and being able to shave my collection down to a reasonable size so that I can play some of these games.

I'd consider getting deeper into it but that would probably not be any time soon.  Thanks for the suggestions though, they are definitely noted....
